
import javax.swing.JButton;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohammad
 */
public class InterfaceGrafica extends javax.swing.JFrame {
    
    /**
     * Creates new form InterfaceGrafica
     */
    public InterfaceGrafica() {
        initComponents();
        setSize(600,400);
        setLocationRelativeTo(null);
        
        btn9.setVisible(false);
    }
    public InterfaceGrafica(int[] lista) {
        initComponents();
        setSize(600,400);
        setLocationRelativeTo(null);
        
        JButton button_array [] = {btn1,btn2,btn3,btn4,btn5,btn6,btn7,btn8,btn9};
        
        //Reordena os números
        for(int i = 0; i <= 8 ; i++){
            button_array[i].setText(Integer.toString(lista[i]));
            if(lista[i] == 0){
                button_array[i].setVisible(false);
            }else{
                button_array[i].setVisible(true);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 3));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(btn3.isVisible()== false){
            btn3.setText(btn6.getText());
            btn6.setVisible(false);
            btn3.setVisible(true);            
        }
        if(btn5.isVisible()== false){
            btn5.setText(btn6.getText());
            btn6.setVisible(false);
            btn5.setVisible(true);            
        }
        if(btn9.isVisible()== false){
            btn9.setText(btn6.getText());
            btn6.setVisible(false);
            btn9.setVisible(true);            
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(btn5.isVisible()== false){
            btn5.setText(btn8.getText());
            btn8.setVisible(false);
            btn5.setVisible(true);            
        }
        if(btn7.isVisible()==false){
            btn7.setText(btn8.getText());
            btn8.setVisible(false);
            btn7.setVisible(true);
        }
        if(btn9.isVisible()==false){
            btn9.setText(btn8.getText());
            btn8.setVisible(false);
            btn9.setVisible(true);
        }
        
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(btn6.isVisible()== false){
            btn6.setText(btn9.getText());
            btn9.setVisible(false);
            btn6.setVisible(true);            
        }
        if(btn8.isVisible()==false){
            btn8.setText(btn9.getText());
            btn9.setVisible(false);
            btn8.setVisible(true);
        }

    }//GEN-LAST:event_btn9ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(btn4.isVisible()== false){
            btn4.setText(btn7.getText());
            btn7.setVisible(false);
            btn4.setVisible(true);            
        }
        if(btn8.isVisible()== false){
            btn8.setText(btn7.getText());
            btn7.setVisible(false);
            btn8.setVisible(true);            
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(btn2.isVisible()== false){
            btn2.setText(btn5.getText());
            btn5.setVisible(false);
            btn2.setVisible(true);            
        }
        if(btn4.isVisible()== false){
            btn4.setText(btn5.getText());
            btn5.setVisible(false);
            btn4.setVisible(true);            
        }
        if(btn6.isVisible()== false){
            btn6.setText(btn5.getText());
            btn5.setVisible(false);
            btn6.setVisible(true);            
        }
        if(btn8.isVisible()== false){
            btn8.setText(btn5.getText());
            btn5.setVisible(false);
            btn8.setVisible(true);            
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(btn1.isVisible()== false){
            btn1.setText(btn4.getText());
            btn4.setVisible(false);
            btn1.setVisible(true);            
        }
        if(btn5.isVisible()== false){
            btn5.setText(btn4.getText());
            btn4.setVisible(false);
            btn5.setVisible(true);            
        }
        if(btn7.isVisible()== false){
            btn7.setText(btn4.getText());
            btn4.setVisible(false);
            btn7.setVisible(true);            
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(btn2.isVisible()== false){
            btn2.setText(btn3.getText());
            btn3.setVisible(false);
            btn2.setVisible(true);            
        }
        if(btn6.isVisible()== false){
            btn6.setText(btn3.getText());
            btn3.setVisible(false);
            btn6.setVisible(true);            
        }
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(btn1.isVisible()== false){
            btn1.setText(btn2.getText());
            btn2.setVisible(false);
            btn1.setVisible(true);            
        }
        if(btn3.isVisible()== false){
            btn3.setText(btn2.getText());
            btn2.setVisible(false);
            btn3.setVisible(true);            
        }
        if(btn5.isVisible()== false){
            btn5.setText(btn2.getText());
            btn2.setVisible(false);
            btn5.setVisible(true);            
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if(btn2.isVisible()== false){
            btn2.setText(btn1.getText());
            btn1.setVisible(false);
            btn2.setVisible(true);            
        }
        if(btn4.isVisible()== false){
            btn4.setText(btn1.getText());
            btn1.setVisible(false);
            btn4.setVisible(true);            
        }
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
